---
img_width: 150
img_height: 150
num_classes: 2
batch_size: 32

train_gen:
  rescale: 0.003921568627
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True

val_gen:
  rescale: 0.003921568627
...
