---
img_width: 150
img_height: 150
batch_size: 25
data_dir: data/flavia/

train_gen:
  rescale: 003921568627
  rotation_range: 30
  height_shift_range: 0.1
  width_shift_range: 0.1
  channel_shift_range: 0.1
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True

val_gen:
  rescale: 003921568627
...
