---
name: flavia


train_dir: data/flavia/train
val_dir: data/flavia/validation
test_dir: data/flavia/test
train_feature: history/flavia_train_resnet50.h5
val_feature: history/flavia_val_resnet50.h5
test_feature: history/flavia_test_resnet50.h5

architecture: resnet50
batch_size: 8
#classifier: LDA
factor: 5
epoch: 100
model_file: classifier.pkl
weight_file: weight.pkl
result_file: result.pkl

gen_params:
  rotation_range: 90
#  width_shift_range: 0.2
#  height_shift_range: 0.2
#  channel_shift_range: 100
#  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True

