---
name: flavia

train_dir: data/flavia/train
test_dir: data/flavia/test
train_feature: history/flavia_train_resnet50.h5
test_feature: history/flavia_test_resnet50.h5

architecture: resnet50
batch_size: 32
#classifier: LDA
epoch: 100
model_file: classifier.pkl
weight_file: weight.pkl
result_file: result.pkl

