---
name: swedish

train_dir: data/swedish/train
test_dir: data/swedish/test
train_feature: history/swedish2_train_resnet50.h5
test_feature: history/swedish2_test_resnet50.h5

architecture: resnet50
batch_size: 8
epoch: 100
model_file: classifier.pkl
weight_file: weight.pkl
result_file: result.pkl