---
name: swedish

train_dir: data/swedish/train
val_dir: data/swedish/validation
test_dir: data/swedish/test
train_feature: history/swedish_train_resnet50.h5
val_feature: history/swedish_val_resnet50.h5
test_feature: history/swedish_test_resnet50.h5

architecture: resnet50
batch_size: 8
epoch: 100
model_file: classifier.pkl
weight_file: weight.pkl
result_file: result.pkl